-- MySQL Script generated by MySQL Workbench
-- 01/11/17 11:36:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wids
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wids
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wids` DEFAULT CHARACTER SET utf8 ;
USE `wids` ;

-- -----------------------------------------------------
-- Table `wids`.`ssid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wids`.`ssid` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `first-time` TEXT(50) NULL DEFAULT NULL,
  `last-time` TEXT(50) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `max-rate` DECIMAL(10,0) NULL DEFAULT NULL,
  `packets` INT(11) NULL DEFAULT NULL,
  `beaconrate` INT(11) NULL DEFAULT NULL,
  `encryption` VARCHAR(45) NULL DEFAULT NULL,
  `essid` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wids`.`wirelessclient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wids`.`wirelessclient` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `number` INT(11) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `first-time` TEXT(50) NULL DEFAULT NULL,
  `last-time` TEXT(50) NULL DEFAULT NULL,
  `client-mac` VARCHAR(45) NULL,
  `client-manuf` VARCHAR(45) NULL,
  `channel` INT(11) NULL DEFAULT NULL,
  `maxseenrate` INT(11) NULL DEFAULT NULL,
  `carrier` VARCHAR(45) NULL,
  `encoding` VARCHAR(45) NULL,
  `LLC` INT(11) NULL,
  `data` INT(11) NULL,
  `crypt` INT(11) NULL,
  `total` INT(11) NULL,
  `fragments` INT(11) NULL,
  `retries` INT(11) NULL,
  `last_signal_dbm` INT(11) NULL,
  `last_noise_dbm` INT(11) NULL,
  `last_signal_rssi` INT(11) NULL,
  `last_noise_rssi` INT(11) NULL,
  `min_signal_dbm` INT(11) NULL,
  `min_noise_dbm` INT(11) NULL,
  `min_signal_rssi` INT(11) NULL,
  `min_noise_rssi` INT(11) NULL,
  `max_signal_dbm` INT(11) NULL,
  `max_noise_dbm` INT(11) NULL,
  `max_signal_rssi` INT(11) NULL,
  `max_noise_rssi` INT(11) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wids`.`wirelessnetwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wids`.`wirelessnetwork` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `number` INT(11) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `first-time` TEXT(50) NULL DEFAULT NULL,
  `last-time` TEXT(50) NULL DEFAULT NULL,
  `BSSID` VARCHAR(45) NULL DEFAULT NULL,
  `manuf` VARCHAR(45) NULL DEFAULT NULL,
  `channel` INT(11) NULL DEFAULT NULL,
  `freqmhz` VARCHAR(45) NULL DEFAULT NULL,
  `maxseenrate` INT(11) NULL DEFAULT NULL,
  `carrier` VARCHAR(45) NULL,
  `encoding` VARCHAR(45) NULL,
  `LLC` INT(11) NULL,
  `data` INT(11) NULL,
  `crypt` INT(11) NULL,
  `total` INT(11) NULL,
  `fragments` INT(11) NULL,
  `retries` INT(11) NULL,
  `datasize` INT(11) NULL DEFAULT NULL,
  `bsstimestamp` VARCHAR(45) NULL DEFAULT NULL,
  `las_signal_dbm` INT(11) NULL,
  `last_noise_dbm` INT(11) NULL,
  `last_signal_rssi` INT(11) NULL,
  `last_noise_rssi` INT(11) NULL,
  `min_signal_dbm` INT(11) NULL,
  `min_noise_dbm` INT(11) NULL,
  `min_signal_rssi` INT(11) NULL,
  `min_noise_rssi` INT(11) NULL,
  `max_signal_dbm` INT(11) NULL,
  `max_noise_dbm` INT(11) NULL,
  `max_signal_rssi` INT(11) NULL,
  `max_noise_rssi` INT(11) NULL,
  `cdp-device` VARCHAR(45) NULL DEFAULT NULL,
  `cdp-portid` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
